# Generated by Django 6.0.5 on 2026-05-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
