# Generated by Django 6.0.5 on 2026-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payaza_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payaza_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payaza_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
