# Generated by Django 6.0.5 on 2026-05-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='position',
            new_name='payout_order',
        ),
        migrations.RenameField(
            model_name='savingsgroup',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('defaulted', 'Defaulted'), ('left', 'Left')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.savingsgroup'),
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='max_members',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingsgroup',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('completed', 'Completed')], default='forming', max_length=20),
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='is_active',
        ),
    ]
